spring:
  application:
    name: bankLans
    security:
      jwt:
        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
        expiration: 86400000 # a day
        refresh-token:
          expiration: 604800000 # 7 days
  datasource:
    url: jdbc:postgresql://localhost:5432/bankLoans
    username: postgres
    password: 181277
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create  # Cambia a 'none', 'create' o 'update' dependiendo del caso
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
    org.hibernate.type.descriptor.sql: trace
