spring:
  application:
    name: bankLans
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # 1 día en milisegundos
      refresh-token:
        expiration: 604800000 # 7 días en milisegundos
  datasource:
    url: jdbc:postgresql://localhost:5432/bankLoans
    username: postgres
    password: 181277
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create # Cambia a 'none', 'create', 'update' o 'validate' según sea necesario
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  config:
    activate:
      on-profile: default

property:
  debug: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      hibernate.type.descriptor.sql: TRACE

